[package]
name = "automata-web"
version = "0.1.0"
edition = "2024"

[dependencies]
automata = {path=".."}
console_error_panic_hook = "0.1.7"
wasm-bindgen = "*"
web-sys = { version = "0.3.83", features = ["Window", "Document", "HtmlElement", "Text"] }
